# Generated by Django 3.1.6 on 2021-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210212_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Computadore'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empregado'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permissõe'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Software'},
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
